-- Auto-generated migration for mysql backend
-- Generated by Orion migration_gen

CREATE TABLE IF NOT EXISTS `workflows` ( `workflow_id` text NOT NULL, `version` int NOT NULL, `name` text NOT NULL, `description` text, `priority` int NOT NULL DEFAULT 0, `status` text NOT NULL DEFAULT 'draft', `rollout_percentage` int NOT NULL DEFAULT 100, `condition_json` text NOT NULL DEFAULT 'true', `tasks_json` text NOT NULL DEFAULT '[]', `tags` text NOT NULL DEFAULT '[]', `continue_on_error` bool NOT NULL DEFAULT FALSE, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`workflow_id`, `version`) );

CREATE TABLE IF NOT EXISTS `channels` ( `channel_id` text NOT NULL, `version` int NOT NULL, `name` text NOT NULL, `description` text, `channel_type` text NOT NULL, `protocol` text NOT NULL, `methods` text, `route_pattern` text, `topic` text, `consumer_group` text, `transport_config_json` text NOT NULL DEFAULT '{}', `workflow_id` text, `config_json` text NOT NULL DEFAULT '{}', `status` text NOT NULL DEFAULT 'draft', `priority` int NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`channel_id`, `version`) );

CREATE TABLE IF NOT EXISTS `connectors` ( `id` text NOT NULL PRIMARY KEY, `name` text NOT NULL UNIQUE, `connector_type` text NOT NULL, `config_json` text NOT NULL DEFAULT '{}', `enabled` bool NOT NULL DEFAULT TRUE, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS `traces` ( `id` text NOT NULL PRIMARY KEY, `channel` text NOT NULL DEFAULT 'default', `channel_id` text, `mode` text NOT NULL DEFAULT 'sync', `status` text NOT NULL DEFAULT 'pending', `input_json` text, `result_json` text, `error_message` text, `duration_ms` double, `started_at` timestamp, `completed_at` timestamp, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS `trace_dlq` (
    `id` VARCHAR(36) NOT NULL PRIMARY KEY,
    `trace_id` VARCHAR(36) NOT NULL,
    `channel` VARCHAR(255) NOT NULL,
    `payload_json` TEXT NOT NULL,
    `metadata_json` TEXT NOT NULL,
    `error_message` TEXT NOT NULL,
    `retry_count` INT NOT NULL DEFAULT 0,
    `max_retries` INT NOT NULL DEFAULT 5,
    `next_retry_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX `idx_workflows_status` ON `workflows` (`status`);
CREATE INDEX `idx_workflows_workflow_id` ON `workflows` (`workflow_id`);
CREATE INDEX `idx_workflows_priority_name` ON `workflows` (`priority` DESC, `name` ASC);
CREATE INDEX `idx_channels_status` ON `channels` (`status`);
CREATE INDEX `idx_channels_name` ON `channels` (`name`);
CREATE INDEX `idx_channels_type_status` ON `channels` (`channel_type`, `status`);
CREATE INDEX `idx_channels_channel_id` ON `channels` (`channel_id`);
CREATE INDEX `idx_channels_route` ON `channels` (`route_pattern`);
CREATE INDEX `idx_channels_topic` ON `channels` (`topic`);
CREATE INDEX `idx_channels_workflow` ON `channels` (`workflow_id`);
CREATE INDEX `idx_traces_status` ON `traces` (`status`);
CREATE INDEX `idx_traces_status_channel` ON `traces` (`status`, `channel`);
CREATE INDEX `idx_traces_channel` ON `traces` (`channel`);
CREATE INDEX `idx_traces_mode` ON `traces` (`mode`);
CREATE INDEX `idx_traces_created_at` ON `traces` (`created_at`);
CREATE INDEX `idx_traces_channel_id` ON `traces` (`channel_id`);

CREATE INDEX `idx_trace_dlq_next_retry` ON `trace_dlq` (`next_retry_at`, `retry_count`);
CREATE INDEX `idx_trace_dlq_channel` ON `trace_dlq` (`channel`);

-- Latest version per workflow_id
CREATE VIEW current_workflows AS
SELECT w.*
FROM workflows w
INNER JOIN (
  SELECT workflow_id, MAX(version) AS max_version
  FROM workflows
  GROUP BY workflow_id
) latest ON w.workflow_id = latest.workflow_id AND w.version = latest.max_version;

-- Latest version per channel_id
CREATE VIEW current_channels AS
SELECT c.*
FROM channels c
INNER JOIN (
  SELECT channel_id, MAX(version) AS max_version
  FROM channels
  GROUP BY channel_id
) latest ON c.channel_id = latest.channel_id AND c.version = latest.max_version;

-- Auto-update updated_at
DELIMITER //
CREATE TRIGGER trg_workflows_updated_at
    BEFORE UPDATE ON workflows
    FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END//

CREATE TRIGGER trg_channels_updated_at
    BEFORE UPDATE ON channels
    FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END//

CREATE TRIGGER trg_connectors_updated_at
    BEFORE UPDATE ON connectors
    FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END//

CREATE TRIGGER trg_traces_updated_at
    BEFORE UPDATE ON traces
    FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END//

CREATE TRIGGER trg_trace_dlq_updated_at
    BEFORE UPDATE ON trace_dlq
    FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END//

-- Single-draft enforcement
CREATE TRIGGER trg_workflows_single_draft
    BEFORE INSERT ON workflows
    FOR EACH ROW
BEGIN
    IF NEW.status = 'draft' THEN
        IF EXISTS (SELECT 1 FROM workflows WHERE workflow_id = NEW.workflow_id AND status = 'draft') THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only one draft version allowed per workflow';
        END IF;
    END IF;
END//

CREATE TRIGGER trg_channels_single_draft
    BEFORE INSERT ON channels
    FOR EACH ROW
BEGIN
    IF NEW.status = 'draft' THEN
        IF EXISTS (SELECT 1 FROM channels WHERE channel_id = NEW.channel_id AND status = 'draft') THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Only one draft version allowed per channel';
        END IF;
    END IF;
END//
DELIMITER ;
