-- Auto-generated migration for postgres backend
-- Generated by Orion migration_gen

CREATE TABLE IF NOT EXISTS "workflows" ( "workflow_id" text NOT NULL, "version" integer NOT NULL, "name" text NOT NULL, "description" text, "priority" integer NOT NULL DEFAULT 0, "status" text NOT NULL DEFAULT 'draft', "rollout_percentage" integer NOT NULL DEFAULT 100, "condition_json" text NOT NULL DEFAULT 'true', "tasks_json" text NOT NULL DEFAULT '[]', "tags" text NOT NULL DEFAULT '[]', "continue_on_error" bool NOT NULL DEFAULT FALSE, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("workflow_id", "version") );

CREATE TABLE IF NOT EXISTS "channels" ( "channel_id" text NOT NULL, "version" integer NOT NULL, "name" text NOT NULL, "description" text, "channel_type" text NOT NULL, "protocol" text NOT NULL, "methods" text, "route_pattern" text, "topic" text, "consumer_group" text, "transport_config_json" text NOT NULL DEFAULT '{}', "workflow_id" text, "config_json" text NOT NULL DEFAULT '{}', "status" text NOT NULL DEFAULT 'draft', "priority" integer NOT NULL DEFAULT 0, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("channel_id", "version") );

CREATE TABLE IF NOT EXISTS "connectors" ( "id" text NOT NULL PRIMARY KEY, "name" text NOT NULL UNIQUE, "connector_type" text NOT NULL, "config_json" text NOT NULL DEFAULT '{}', "enabled" bool NOT NULL DEFAULT TRUE, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS "traces" ( "id" text NOT NULL PRIMARY KEY, "channel" text NOT NULL DEFAULT 'default', "channel_id" text, "mode" text NOT NULL DEFAULT 'sync', "status" text NOT NULL DEFAULT 'pending', "input_json" text, "result_json" text, "error_message" text, "duration_ms" double precision, "started_at" timestamp, "completed_at" timestamp, "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE IF NOT EXISTS "trace_dlq" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "trace_id" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "payload_json" TEXT NOT NULL,
    "metadata_json" TEXT NOT NULL DEFAULT '{}',
    "error_message" TEXT NOT NULL,
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "max_retries" INTEGER NOT NULL DEFAULT 5,
    "next_retry_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "idx_workflows_status" ON "workflows" ("status");
CREATE INDEX "idx_workflows_workflow_id" ON "workflows" ("workflow_id");
CREATE INDEX "idx_workflows_priority_name" ON "workflows" ("priority" DESC, "name" ASC);
CREATE INDEX "idx_channels_status" ON "channels" ("status");
CREATE INDEX "idx_channels_name" ON "channels" ("name");
CREATE INDEX "idx_channels_type_status" ON "channels" ("channel_type", "status");
CREATE INDEX "idx_channels_channel_id" ON "channels" ("channel_id");
CREATE INDEX "idx_channels_route" ON "channels" ("route_pattern");
CREATE INDEX "idx_channels_topic" ON "channels" ("topic");
CREATE INDEX "idx_channels_workflow" ON "channels" ("workflow_id");
CREATE INDEX "idx_traces_status" ON "traces" ("status");
CREATE INDEX "idx_traces_status_channel" ON "traces" ("status", "channel");
CREATE INDEX "idx_traces_channel" ON "traces" ("channel");
CREATE INDEX "idx_traces_mode" ON "traces" ("mode");
CREATE INDEX "idx_traces_created_at" ON "traces" ("created_at");
CREATE INDEX "idx_traces_channel_id" ON "traces" ("channel_id");

CREATE INDEX idx_channels_route_partial ON channels(route_pattern) WHERE route_pattern IS NOT NULL;
CREATE INDEX idx_channels_topic_partial ON channels(topic) WHERE topic IS NOT NULL;
CREATE INDEX idx_channels_workflow_partial ON channels(workflow_id) WHERE workflow_id IS NOT NULL;
CREATE INDEX idx_traces_channel_id_partial ON traces(channel_id) WHERE channel_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS "audit_logs" (
    "id" text NOT NULL PRIMARY KEY,
    "principal" text NOT NULL,
    "action" text NOT NULL,
    "resource_type" text NOT NULL,
    "resource_id" text NOT NULL,
    "details" text,
    "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "idx_trace_dlq_next_retry" ON "trace_dlq" ("next_retry_at") WHERE "retry_count" < "max_retries";
CREATE INDEX "idx_trace_dlq_channel" ON "trace_dlq" ("channel");
CREATE INDEX "idx_audit_logs_created_at" ON "audit_logs" ("created_at");
CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" ("resource_type", "resource_id");

-- Latest version per workflow_id
CREATE VIEW current_workflows AS
SELECT w.*
FROM workflows w
INNER JOIN (
  SELECT workflow_id, MAX(version) AS max_version
  FROM workflows
  GROUP BY workflow_id
) latest ON w.workflow_id = latest.workflow_id AND w.version = latest.max_version;

-- Latest version per channel_id
CREATE VIEW current_channels AS
SELECT c.*
FROM channels c
INNER JOIN (
  SELECT channel_id, MAX(version) AS max_version
  FROM channels
  GROUP BY channel_id
) latest ON c.channel_id = latest.channel_id AND c.version = latest.max_version;

-- Generic updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_workflows_updated_at
    BEFORE UPDATE ON workflows
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_channels_updated_at
    BEFORE UPDATE ON channels
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_connectors_updated_at
    BEFORE UPDATE ON connectors
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_traces_updated_at
    BEFORE UPDATE ON traces
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_trace_dlq_updated_at
    BEFORE UPDATE ON trace_dlq
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Single-draft enforcement via partial unique indexes
CREATE UNIQUE INDEX idx_workflows_single_draft
    ON workflows (workflow_id) WHERE status = 'draft';

CREATE UNIQUE INDEX idx_channels_single_draft
    ON channels (channel_id) WHERE status = 'draft';
