{{- if not .Values.storage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orion.fullname" . }}-storage
  labels:
    {{- include "orion.labels" . | nindent 4 }}
type: Opaque
stringData:
  storage-url: {{ include "orion.storageUrl" . | quote }}
{{- end }}
{{- if and .Values.adminAuth.apiKeys (not .Values.adminAuth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orion.fullname" . }}-admin-auth
  labels:
    {{- include "orion.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys: {{ join "," .Values.adminAuth.apiKeys | quote }}
{{- end }}
